### PR TITLE
Track nested meta-tracing states.

### LINKED ISSUE #1571: meta_framegap.lua deopt crash
With today's yklua (e99ff2) and yk (3dc428) an OpenResty test causes a deopt crash:

```
$ YK_OPT=0 YKD_SERIALISE_COMPILATION=1 ~/research/yklua/src/lua luajit2-test-suite/test/misc/meta_framegap.lua
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x64/deopt.rs:40:30:
no entry found for key
```

To get the test file, you can use the branch from [this PR](https://github.com/ykjit/yklua-tests/pull/1)

(Once it's merged, you can just use `main`)

### PR DESCRIPTION
**Pull request by ltratt**
Previously we -- well, this one is entirely my fault, so "I"! -- tracked per-thread meta-tracing state as a single `MTThreadState` that we updates as necessary. This doesn't work when we have nested execution, tracing and the like, as the bug in #1571 highlighted.

This commit moves us to a stack of `MTThreadState`s. The basic idea is that the stack always has at least one element: `Interpreting`. As we go through other states, we push / pop as appropriate. The test below (from Edd and Lukas) fails on `master` but is fixed by this commit.

The implementation is a bit more awkward than one might hope as naive implementations either:

  1. Spread lots of knowledge about the stack around the code. That's a disaster waiting to happen.
  2. Run into borrow checker problems.

This commit gets around this in two phases:

  1. We pass closures to `MTThread` which can peek at the current `MTThreadState` (which isn't `Copy`!).
  2. Those closures return the "things" we need to update outside that context.

This is a bit awkward, and perhaps there's a better API, but this one is at least safe.

Fixes #1571.

### CODE REVIEW

File: ykrt/src/mt.rs [hunk 1]
```diff
@@ -867,6 +877,12 @@ impl MT {
         }
     }
 
+    /// Inform this `MT` instance that `deopt` has occurred: this updates the stack of
+    /// [MTThreadState]s.
+    pub(crate) fn deopt(self: &Arc<Self>) {
+        MTThread::with(|mtt| mtt.pop_tstate());
```
Comment (vext01) [inline ykrt/src/mt.rs:883]: shall we assert that the top of the stack is `Executing` here for sanity?

**Comment by vext01** [comment]
I'm OK with this, but @ptersilie should have a look before we merge.

File: ykrt/src/mt.rs (hunk 1 above)
Comment (ltratt) [reply ykrt/src/mt.rs]: Fixed in 116ba0371f9c1f5a03b5b83ee986907ca4065a0b.

Comment (vext01) [reply ykrt/src/mt.rs]: Thanks!

**Comment by ptersilie** [comment]
Looks good to me.

**Comment by vext01** [comment]
If you are ready @ltratt, please squash.

**Comment by ltratt** [comment]
Squashed.
